### ISSUE TITLE
Github Pages not configured

### ISSUE THREAD

**Issue by nalzok** [AtomXT/ECNU-Course-Info#17]
Dear all,

Pull request #16 should have prepared this repo for publishing its own Pages site, but it doesn't seem to be online. I suppose this feature has to be manually enabled by the repo owner.

@AtomXT Can you follow the instructions [here][1] to enable GitHub Pages for this repo so that we can publish the site from master? Alternatively, [list me as a collaborator][2] so that I can help out.

PS: 大家觉得我们应该讲中文还是讲英文呀？个人感觉在 GitHub 上用中文很违和，毕竟整个用户界面都是英文的，而且有些人也会觉得这样不礼貌。但话说回来，如果在这个仓库里的其他人都用中文的话，那么讲英文好像就更不合适了:eyes:

Cheers,
Qingyao

  [1]: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages
  [2]: https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository

**Comment by AtomXT** [comment]
I'm not sure whether it has been solved now. @nalzok Can you confirm it for me?
And I have invited you as a collaboratot.
As for the language, I think it's better to use English to communicate. when in Github, do as the githubers do. But since our users are almost all Chinese, it should be ok to use Chinese in other ciucumstances.

**Comment by nalzok** [comment]
>  @nalzok Can you confirm it for me?

Yeah, it works! Here's the link: https://atomxt.github.io/ECNU-Course-Info/

> As for the language, I think it's better to use English to communicate. when in Github, do as the githubers do. But since our users are almost all Chinese, it should be ok to use Chinese in other ciucumstances.

Makes sense to me. Let's just use whatever language we are comfortable with.
